---
title: "Untitled"
author: "Weijia Xiong"
date: "9/19/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Import datasets
```{r}

options(tibble.print_min = 3)

litters_data = read_csv("./data/FAS_litters.csv",
  col_types = "ccddiiii")
litters_data = janitor::clean_names(litters_data)

pups_data = read_csv("./data/FAS_pups.csv",
  col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)
```


## Selecting
```{r}
select(litters_data, group, litter_number, gd0_weight, pups_born_alive)

select(litters_data, group:gd_of_birth)

select(litters_data, gd0_weight,starts_with("pups"))

select(litters_data,litter_number, group, gd0_weight)

select(litters_data,litter_number,group,everything())  ## everything and put litter_number first.

select(litters_data,-group) ## remove

litters_selected  = select(litters_data,litter_number, gd0_weight:pups_born_alive)  # didn't change litters_data


select(litters_data, GROUP = group, litter_number)  ## rename & select variables
rename(litters_data,GROUP = group) ##just rename 

##starts_with(), ends_with(), and contains() 
```


## Learning Assessment



```{r}
select(pups_data,litter_number,sex,pd_ears)
```



## Filter


```{r}
filter(litters_data,group == "Con7") ##check xxx is equal to xxx? when this is true, keeps ...

filter(litters_data,gd_of_birth == 20)


filter(litters_data, pups_born_alive >= 2)

filter(litters_data, pups_born_alive == 6, group == "Con7")
filter(litters_data, pups_born_alive == 6 & group == "Con7")

filter(litters_data, group %in% c("Con7", "Con8"))
filter(litters_data, group == "Con7" | group == "Con8")


filter(litters_data,pups_born_alive >= 4, pups_born_alive <= 6)

filter(litters_data,gd0_weight + gd18_weight > 50)


## missing data
# don't do this 
# filter(litters_data,!is.na(gd0_weight))

drop_na(litters_data, gd0_weight)  ##remove rows

```

## Learning Assessment 2

```{r}
filter(pups_data,sex == 1)
filter(pups_data, pd_walk < 11, sex == 2)
```




## Mutate
```{r}


mutate(
  litters_data,
  wt_gain = gd18_weight -  gd0_weight,
  group = str_to_lower(group))
```


## Arrange 

```{r}
arrange(litters_data,pups_born_alive)

arrange(litters_data, desc(pups_born_alive))   ## descending
arrange(litters_data,pups_born_alive, gd0_weight)

```




